// Generated by https://quicktype.io

export interface ResultBeneficio {
    ok:        boolean;
    msg:       string;
    beneficio: Beneficio[];
}
export interface ResultBeneficioInd {
    ok:        boolean;
    msg:       string;
    beneficio: Beneficio;
}

export interface Beneficio {
    _id:         string;
    title:       string;
    descripcion: string;
    select:      boolean;
    position:    number;
    estado:      boolean;
    img?:        string;
}
