// Generated by https://quicktype.io

export interface ResultGeneral {
    ok:     boolean;
    msg:    string;
    modelo: General[];
}

export interface General {
    _id:         string;
    title:       string;
    descripcion: string;
    select:      boolean;
    position:    number;
    estado:      boolean;
    logo?:       string;
    img?:        string;
}
