// Generated by https://quicktype.io

export interface ResultLugar {
    ok:        boolean;
    msg:       string;
    ubicacion: Ubicacion[];
}
export interface ResultLugarInd {
    ok:        boolean;
    msg:       string;
    ubicacion: Ubicacion;
}

export interface Ubicacion {
    _id:     string;
    title:   string;
    address: string;
    lat:     number;
    lng:     number;
    color:   string;
    select:  boolean;
    position?: Number;
}

export interface Lugar{
    _id?:string,
    title:string,
    address:string,
    lng: number,
    lat:number,
    color: string,
    select:boolean,
    position?: Number
}
// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface RespMarcadores {
    [key:string]:Lugar
}
