// Generated by https://quicktype.io

export interface ResultMailbox {
    ok:      boolean;
    msg:     string;
    mensaje: Mensaje[];
}
export interface ResultMailboxInd {
    ok:      boolean;
    msg:     string;
    mensaje: Mensaje;
}
export interface Mensaje {
    _id:      string;
    name:     string;
    correo:   string;
    celular:  string;
    servicio: Servicio;
    mensaje:  string;
    position: number;
    date:     string;
    visto:    boolean;
    empresa:  string;
}

export interface Servicio {
    _id:   string;
    title: string;
}
