// Generated by https://quicktype.io

export interface ResultModelo {
    ok:     boolean;
    msg:    string;
    modelo: Modelo;
}

export interface Modelo {
    _id?:         string;
    title?:       string;
    descripcion?: string;
    select?:      boolean;
    position?:    number;
    estado?:      boolean;
    img?:         string;
    subject?:     string;
    html?:        string
    name?:     string;
    lastname?: string;
    usuario?:  string;
    rol?:      string;
    password?: string;
    enlace?: string;
    logo?: string;
}
