// Generated by https://quicktype.io

export interface ResultNosotros {
    ok:       boolean;
    msg:      string;
    nosotros: Nosotro[];
}
export interface ResultNosotrosInd {
    ok:       boolean;
    msg:      string;
    nosotros: Nosotro;
}

export interface Nosotro {
    _id:         string;
    title:       string;
    descripcion: string;
    position:    number;
    estado:      boolean;
    img?:        string;
    select?:     string;
}
