// Generated by https://quicktype.io

export interface ResultPersonal {
    ok:       boolean;
    msg:      string;
    personal: Personal[];
}
export interface ResultPersonalInd {
    ok:       boolean;
    msg:      string;
    personal: Personal;
}
export interface Personal {
    _id:         string;
    correo:      string;
    celular:     string;
    descripcion: string;
    imgcontact:  string;
    imgpri:      string;
    logo:        string;
}
