// Generated by https://quicktype.io

export interface ResultTecnologia {
    ok:         boolean;
    msg:        string;
    tecnologia: Tecnologia[];
}
export interface ResultTecnologiaInd {
    ok:         boolean;
    msg:        string;
    tecnologia: Tecnologia;
}

export interface Tecnologia {
    _id:         string;
    title:       string;
    descripcion: string;
    select:      boolean;
    position:    number;
    estado:      boolean;
    img?:        string;
}
