// Generated by https://quicktype.io

export interface ResultUsuario {
    ok:      boolean;
    msg:     string;
    usuario: Usuario[];
}
export interface ResultUsuarioInd {
    ok:      boolean;
    msg:     string;
    usuario: Usuario;
}

export interface Usuario {
    _id:      string;
    name:     string;
    lastname: string;
    usuario:  string;
    rol:      string;
    estado:   boolean;
    password: string;
    img?:string;
}
