// Generated by https://quicktype.io

export interface ResultWelcome {
    ok:      boolean;
    welcome: Welcome[];
}
export interface ResultWelcomeInd {
    ok:      boolean;
    welcome: Welcome;
    msg?: string;
}

export interface Welcome {
    _id:     string;
    subject: string;
    html:    string;
    img:     string;
}
